---
<(META)>:
  docid: '6461e864-070f-422b-b26d-2b8631369698'
  name:
  description: >
  expirary: <[expiration]>
  version: '0.0.0.0.0.0'
  authority: document|this
  security: sec|lvl2
  <(WT)>: -32
perf:
  cores: 4
asprime:
user: <[LEXIvrs]>/bear/<[prime]>/<[prime]>.yaml
prime: <[prime]>
things:
  <(LCLvrs)>: <[<[SB]>:.DATAvrs]>
  <(PATH)>: WDM/thingery_com/content/
  whats:
    abstracts:
      digitialsystems:
        <(PATH)>:
          - filetypes.yaml
examine:
  store:
    load_things:
      - files.yaml
      - dbs.yaml
      - paths.yaml
filetypes: filetypes.yaml
syntaxtypes: syntax.yaml
